services:
  - type: web
    name: jargon-bingo-backend
    env: python
    startCommand: bash -lc "pip install -r requirements.txt && python app.py"
    envVars:
      - key: ASSEMBLYAI_API_KEY
        sync: false