services:
  - type: web
    name: jargon-bingo-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: ASSEMBLYAI_API_KEY
        sync: false