services:
  - type: web
    name: jargon-bingo-backend
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: ASSEMBLYAI_API_KEY
        sync: false